FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential cmake curl ninja-build \
    llvm clang lld \
    git libgmp-dev pkg-config uuid uuid-dev wget \
    openjdk-8-jdk python3-pip \
    m4 \
    zlib1g zlib1g-dev \
    libboost-dev \
    openssl \
    doxygen \
    wine \
    mingw-w64 mingw-w64-common mingw-w64-x86-64-dev \
    python3-sphinx \
    liblua5.2 lua5.2 liblua5.3 lua5.3 \
    texlive texlive-xetex texlive-lang-cyrillic cm-super fonts-freefont-otf latexmk xindy && \
    pip3 install toml recommonmark
