# Toolchain for MacOS

set(CMAKE_SYSTEM_NAME Darwin)

if (CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
    set(COMPILER_PREFIX "arm64-apple-darwin22")
else ()
    set(COMPILER_PREFIX "x86_64-apple-darwin22")
endif ()

# which compilers to use for C and C++
find_program(CMAKE_C_COMPILER HINTS ${CMAKE_FIND_ROOT_PATH} NAMES ${COMPILER_PREFIX}-clang REQUIRED)
find_program(CMAKE_CXX_COMPILER HINTS ${CMAKE_FIND_ROOT_PATH} NAMES ${COMPILER_PREFIX}-clang++ REQUIRED)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)